# Generated by Django 5.0.1 on 2024-02-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcategory',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
