# Generated by Django 5.0.1 on 2024-02-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
