# Generated by Django 5.0.1 on 2024-02-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_quiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
