# Generated by Django 5.0.1 on 2024-02-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_paper',
        ),
        migrations.AddField(
            model_name='question',
            name='question_paper',
            field=models.ManyToManyField(to='question.questionpaper'),
        ),
    ]
